/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommandInput.java
 *
 * Created on 15-apr-2011, 14:36:24
 */
package assignment2.gui;

import assignment2.command.CommandInputControl;

/**
 *
 * @author Ricardo Vink
 */
public class CommandInput extends javax.swing.JPanel
{

	/** Creates new form CommandInput */
	public CommandInput()
	{
		initComponents();
	}

	public void setFocus()
	{
		txtCommandInput.requestFocusInWindow();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblCommand = new javax.swing.JLabel();
    txtCommandInput = new javax.swing.JTextField();
    btnExecute = new javax.swing.JButton();

    lblCommand.setText("Command");

    txtCommandInput.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txtCommandInputKeyPressed(evt);
      }
    });

    btnExecute.setText("Execute");
    btnExecute.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExecuteActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(lblCommand)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtCommandInput, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnExecute)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(lblCommand)
        .addComponent(txtCommandInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(btnExecute))
    );
  }// </editor-fold>//GEN-END:initComponents

		private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
			CommandInputControl cic = new CommandInputControl(txtCommandInput.getText());
			cic.checkCommand();
			txtCommandInput.setText("");
		}//GEN-LAST:event_btnExecuteActionPerformed

		private void txtCommandInputKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtCommandInputKeyPressed
		{//GEN-HEADEREND:event_txtCommandInputKeyPressed
			if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
			{
				btnExecuteActionPerformed(null);
			}
		}//GEN-LAST:event_txtCommandInputKeyPressed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnExecute;
  private javax.swing.JLabel lblCommand;
  private javax.swing.JTextField txtCommandInput;
  // End of variables declaration//GEN-END:variables
}
