package assignment2.gui;

import assignment2.Facade;
import java.util.*;
import javax.swing.JTextArea;

public class LogOutput extends JTextArea implements Observer
{

	/** Creates new form LogOutput */
	public LogOutput()
	{
		initComponents();
	}

	public void update(Observable o, Object arg)
	{
		printLog();
	}

	public void printLog()
	{
		setText("");
		Facade f = new Facade();
		ArrayList<String> log = f.getLog();

		for (int i = 0; i < log.size(); i++)
		{
			if (i == 0)
			{
				setText(log.get(i));
			}
			else
			{
				setText(getText() + "\n\r" + log.get(i));
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setText("Type 'help' for available commands!");
    setBorder(javax.swing.BorderFactory.createEtchedBorder());
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
