package assignment2.gui;

import assignment2.Facade;
import assignment2.vehicle.*;
import java.awt.Graphics;
import java.util.*;

public class VisualOutput extends javax.swing.JPanel implements Observer
{
	/** Creates new form VisualOutput */
	public VisualOutput()
	{
		initComponents();
	}

	public void update(Observable o, Object arg)
	{
		paint();
	}

	public void paint()
	{
		Facade f = new Facade();
		HashMap<String, Vehicle> vehicles = f.getVehicles();
		Graphics graphics = getGraphics();
		graphics.clearRect(1, 1, this.getSize().width, this.getSize().height);
		int currentLine = 0;

		for (String key : vehicles.keySet())
		{
			try
			{
				Train t = (Train)vehicles.get(key);
				t.draw(graphics, currentLine, 0);
				
				ArrayList<Wagon> wagons = t.getWagons();
				for (int i = 0; i < wagons.size(); i++)
				{
					Wagon w = wagons.get(i);
					w.draw(graphics, currentLine, (i + 1));
				}
				currentLine++;
			}
			catch(Exception e){}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setPreferredSize(new java.awt.Dimension(2048, 2048));
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentMoved(java.awt.event.ComponentEvent evt) {
        formComponentMoved(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 308, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 181, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

	private void formComponentMoved(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentMoved
	{//GEN-HEADEREND:event_formComponentMoved
		paint();
	}//GEN-LAST:event_formComponentMoved

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
